# Generated by Django 5.1.7 on 2025-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pen_tester", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subnet", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished", models.BooleanField(default=False)),
                ("results", models.JSONField(default=list)),
            ],
        ),
    ]
