# Generated by Django 5.1.7 on 2025-07-27 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pen_tester", "0002_discoveryjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="target",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="last_discovered",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
