# Generated by Django 5.1.7 on 2025-08-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pen_tester", "0004_target_hostname_target_last_scanned_at_and_more"),
        ("pen_tester", "0004_target_summary_fields"),
    ]

    operations = []
