# Generated by Django 5.1.7 on 2025-08-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pen_tester", "0005_merge_20250831_1906"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="target",
            name="hostname",
        ),
        migrations.RemoveField(
            model_name="target",
            name="last_scanned_at",
        ),
        migrations.RemoveField(
            model_name="target",
            name="latency_ms",
        ),
        migrations.RemoveField(
            model_name="target",
            name="mac_address",
        ),
        migrations.RemoveField(
            model_name="target",
            name="open_ports",
        ),
        migrations.RemoveField(
            model_name="target",
            name="port_count",
        ),
        migrations.RemoveField(
            model_name="target",
            name="vendor",
        ),
    ]
