# Generated by Django 5.1.7 on 2025-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("commit", models.CharField(max_length=40)),
                ("branch", models.CharField(max_length=40)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                ("deployed_by", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
