# Generated by Django 5.1.7 on 2025-04-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="balance",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
