# Generated by Django 5.1.4 on 2024-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange", models.CharField(max_length=50)),
                ("account_id", models.CharField(blank=True, max_length=255, null=True)),
                ("asset", models.CharField(max_length=50)),
                ("balance", models.DecimalField(decimal_places=8, max_digits=20)),
                ("converted_zar", models.DecimalField(decimal_places=2, max_digits=20)),
                ("converted_usd", models.DecimalField(decimal_places=2, max_digits=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LunoPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair", models.CharField(max_length=10)),
                ("ask_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bid_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_trade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange", models.CharField(max_length=50)),
                (
                    "zar_to_usd_rate",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "total_converted_zar",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "total_converted_usd",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("balance", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "exchange_rates_zar",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("orders", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "binance_balances",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "binance_total_converted_usd",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "binance_total_converted_zar",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "grand_total_zar",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "grand_total_history",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("value_change", models.DecimalField(decimal_places=2, max_digits=20)),
                ("went_up", models.DecimalField(decimal_places=2, max_digits=20)),
                ("profit_loss", models.CharField(max_length=50)),
                ("money_in", models.CharField(max_length=50)),
                ("money_out", models.CharField(max_length=50)),
                ("combined_balance", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
