# Generated by Django 5.1.7 on 2026-01-15 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("author", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu", models.FloatField(help_text="CPU usage percentage")),
                ("memory", models.FloatField(help_text="Memory usage percentage")),
                ("disk", models.FloatField(help_text="Disk usage percentage")),
                ("uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                ("bytes_sent", models.BigIntegerField(blank=True, null=True)),
                ("bytes_recv", models.BigIntegerField(blank=True, null=True)),
                ("db_latency_ms", models.FloatField(blank=True, null=True)),
                (
                    "disk_read",
                    models.BigIntegerField(
                        blank=True, help_text="Disk read bytes", null=True
                    ),
                ),
                (
                    "disk_write",
                    models.BigIntegerField(
                        blank=True, help_text="Disk write bytes", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
