# Generated by Django 5.1.1 on 2024-09-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange", models.CharField(max_length=50)),
                ("account_id", models.CharField(max_length=255)),
                ("asset", models.CharField(max_length=50)),
                ("balance", models.DecimalField(decimal_places=8, max_digits=20)),
                ("converted_zar", models.DecimalField(decimal_places=2, max_digits=20)),
                ("converted_usd", models.DecimalField(decimal_places=2, max_digits=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
