# Generated by Django 5.1.7 on 2025-05-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_quote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CryptoBalance",
        ),
    ]
