# Generated by Django 5.1.7 on 2025-05-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_quote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CryptoBalance",
        ),
        migrations.DeleteModel(
            name="LunoPrice",
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
