# Generated by Django 5.1.7 on 2025-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_systemmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmetric",
            name="bytes_recv",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemmetric",
            name="bytes_sent",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemmetric",
            name="db_latency_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemmetric",
            name="uptime_seconds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
