# Generated by Django 5.1.1 on 2024-09-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cryptobalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptobalance",
            name="account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
