# Generated by Django 5.1.7 on 2025-06-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_systemmetric_bytes_recv_systemmetric_bytes_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmetric",
            name="disk_read",
            field=models.BigIntegerField(
                blank=True, help_text="Disk read bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemmetric",
            name="disk_write",
            field=models.BigIntegerField(
                blank=True, help_text="Disk write bytes", null=True
            ),
        ),
    ]
