# Generated by Django 5.1.7 on 2025-05-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_cryptobalance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
