# Generated by Django 5.1.7 on 2025-05-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_stats"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LunoPrice",
        ),
    ]
