# Generated by Django 5.1.7 on 2025-06-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_attachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
