# Generated by Django 5.1.7 on 2025-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="exchange",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
