# Generated by Django 5.1.1 on 2024-09-14 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="asset",
            name="converted_usd",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="converted_zar",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="exchange",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="asset",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="price",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
