# Generated by Django 5.1.7 on 2025-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_asset_description_alter_asset_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
    ]
