# Generated by Django 5.1.1 on 2024-09-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_account_id_asset_balance_asset_converted_usd_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="account_id",
        ),
    ]
