# Generated by Django 5.1.7 on 2025-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_alter_asset_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="converted_usd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="converted_zar",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
    ]
