# Generated by Django 5.1.1 on 2024-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_remove_asset_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
