# Generated by Django 5.1.1 on 2024-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="exchange",
            field=models.CharField(max_length=50),
        ),
    ]
