# Generated by Django 5.1.1 on 2024-09-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_asset_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="converted_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="converted_zar",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
