# Generated by Django 5.1.1 on 2024-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_alter_asset_converted_usd_alter_asset_converted_zar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="price",
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
