# Generated by Django 5.1.7 on 2025-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_cryptostats_binance_total_converted_zar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="binance_balances",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="binance_total_converted_usd",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="binance_total_converted_zar",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="combined_balance",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="description",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="exchange_rates_zar",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="grand_total_history",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="grand_total_zar",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="total_converted_usd",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="total_converted_zar",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="value_change",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="went_up",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="zar_to_usd_rate",
        ),
    ]
