# Generated by Django 5.1.1 on 2024-09-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_alter_asset_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="price",
        ),
    ]
