# Generated by Django 5.1.1 on 2024-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_remove_asset_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="price",
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
