# Generated by Django 5.1.7 on 2025-05-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_remove_asset_binance_balances_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptostats",
            old_name="total_converted_zar",
            new_name="luno_total_converted_zar",
        ),
    ]
