# Generated by Django 5.1.7 on 2025-05-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assets",
            "0010_rename_total_converted_zar_cryptostats_luno_total_converted_zar",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptostats",
            name="luno_total_converted_zar",
        ),
    ]
