# Generated by Django 5.1.7 on 2025-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_remove_cryptostats_luno_total_converted_zar"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptostats",
            name="luno_total_converted_zar",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
