# Generated by Django 5.1.7 on 2025-05-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_cryptostats_luno_total_converted_zar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptostats",
            name="binance_total_converted_zar",
        ),
    ]
