# Generated by Django 5.1.7 on 2025-08-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("due_at", models.DateTimeField()),
                (
                    "source_app",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "severity",
                    models.CharField(blank=True, default="info", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
