# Generated by Django 5.1.7 on 2025-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
