# Generated by Django 5.1.7 on 2025-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
