# Generated by Cursor on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("to_do", "0002_todo_user"),
	]

	operations = [
		migrations.AddField(
			model_name="todo",
			name="priority",
			field=models.CharField(
				choices=[("low", "Low"), ("high", "High")],
				default="low",
				max_length=10,
			),
		),
	]

