# Generated by Django 5.1.1 on 2024-09-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0004_credit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credit",
        ),
    ]
