# Generated by Django 5.1.1 on 2024-09-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellables", "0003_alter_sellable_sold_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellable",
            name="balance",
        ),
    ]
