# Generated by Django 5.1.1 on 2024-09-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellables", "0004_remove_sellable_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellable",
            name="condition",
        ),
    ]
