# Generated by Django 5.1.1 on 2024-10-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellables", "0007_sellable_sold_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellable",
            name="price",
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="sellable",
            name="sold_price",
            field=models.DecimalField(
                decimal_places=12, default=0, max_digits=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="SellableImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="sellable_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sellable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="sellables.sellable",
                    ),
                ),
            ],
        ),
    ]
