# Generated by Cursor on 2026-01-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("items", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="SkuCatalog",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("sku", models.CharField(max_length=64, unique=True)),
				("description", models.CharField(max_length=255)),
				("model", models.CharField(blank=True, max_length=128)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
			options={"ordering": ["sku"]},
		),
		migrations.AddField(
			model_name="item",
			name="sku_catalog",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="items",
				to="items.skucatalog",
			),
		),
		migrations.AddField(
			model_name="item",
			name="sku",
			field=models.CharField(blank=True, max_length=64),
		),
		migrations.AddField(
			model_name="item",
			name="model",
			field=models.CharField(blank=True, max_length=128),
		),
		migrations.AddField(
			model_name="item",
			name="sku_description",
			field=models.CharField(blank=True, max_length=255),
		),
	]

