# Generated by Django 5.1.7 on 2025-09-21 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="check_in_time",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="check_out_time",
        ),
        migrations.CreateModel(
            name="AttendanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="time_tracker.attendancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time", "-id"],
            },
        ),
    ]
