# Generated by Django 5.1.7 on 2025-07-16 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera",
            name="ip_address",
            field=models.GenericIPAddressField(default="1.2.3.4"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera",
            name="password",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera",
            name="username",
            field=models.CharField(default="dean", max_length=100),
            preserve_default=False,
        ),
    ]
