# Generated by Django 5.1.7 on 2025-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cameras",
            "0002_camera_created_at_camera_ip_address_camera_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="rtsp_url",
            field=models.CharField(max_length=512),
        ),
    ]
