# Generated by Django 5.1.7 on 2026-01-15 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField()),
                ("path", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("level", models.CharField(max_length=50)),
                ("pathname", models.TextField(blank=True, null=True)),
                ("lineno", models.IntegerField(blank=True, null=True)),
                ("func_name", models.CharField(blank=True, max_length=255, null=True)),
                ("module", models.CharField(blank=True, max_length=100, null=True)),
                ("exception", models.TextField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "exception_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exception_value", models.TextField(blank=True, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("view_name", models.CharField(blank=True, max_length=255, null=True)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("headers", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g. ZenQuotes)", max_length=100
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("execution_time_ms", models.FloatField(blank=True, null=True)),
                ("response_success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UMLTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Generate UML Diagram",
                "verbose_name_plural": "UML Diagram Generator",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("object_repr", models.TextField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("remote_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("view_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("referrer", models.URLField(blank=True, null=True)),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_manual_action", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
