# Generated by Django 5.1.7 on 2025-05-31 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="method",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="errorlog",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
