# Generated by Django 5.1.7 on 2025-05-31 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_errorlog_method_errorlog_status_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="func_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="level",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="errorlog",
            name="lineno",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="pathname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
