# Generated by Django 5.1.7 on 2025-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_errorlog_func_name_errorlog_level_errorlog_lineno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="exception",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="module",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
