# Generated by Django 5.1.7 on 2025-06-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_errorlog_exception_errorlog_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="object_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
