# Generated by Django 5.1.7 on 2025-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_errorlog_exception_type_errorlog_exception_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="headers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="request_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="view_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
