# Generated by Django 5.1.7 on 2025-06-03 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_errorlog_headers_errorlog_request_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g. ZenQuotes)", max_length=100
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("execution_time_ms", models.FloatField(blank=True, null=True)),
                ("response_success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
