# Generated by Django 5.1.7 on 2025-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_externalservicelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_repr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="remote_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="view_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
