# Generated by Django 5.1.7 on 2025-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auditlog_changes_auditlog_object_repr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="is_manual_action",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="referrer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
