# Generated by Django 5.1.7 on 2025-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_auditlog_is_manual_action_auditlog_referrer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UMLTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Generate UML Diagram",
                "verbose_name_plural": "UML Diagram Generator",
            },
        ),
    ]
