# Generated by Django 5.1.7 on 2026-01-15 13:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("horsten_homes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Work"),
                            ("floorplan", "Floorplan"),
                            ("finance", "Finance"),
                            ("expense", "Expense"),
                            ("invoice", "Invoice"),
                            ("leases", "Leases"),
                            ("deeds", "Deeds"),
                            ("legal", "Legal"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "door",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="horsten_homes.door",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="horsten_homes.property",
                    ),
                ),
            ],
        ),
    ]
