# Generated by Django 5.1.7 on 2025-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("work", "Work"),
                    ("finance", "Finance"),
                    ("legal", "Legal"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
