# Generated by Django 5.1.7 on 2025-06-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
    ]
