# Generated by Django 5.1.7 on 2025-06-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_uploadeddocument"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedDocument",
        ),
    ]
