# Generated by Django 5.1.7 on 2025-07-09 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_delete_uploadeddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="documents/%Y/%m/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
