# Generated by Django 5.1.7 on 2025-07-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_folder_storedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storedfile",
            name="folder",
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
        migrations.DeleteModel(
            name="StoredFile",
        ),
    ]
