# Generated by Django 5.1.7 on 2025-10-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_remove_storedfile_folder_delete_folder_and_more"),
        (
            "horsten_homes",
            "0002_door_doorpipeline_estateagent_managingagent_property_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="door",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="horsten_homes.door",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("work", "Work"),
                    ("floorplan", "Floorplan"),
                    ("finance", "Finance"),
                    ("legal", "Legal"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
