# Generated by Django 5.1.7 on 2025-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_document_door_alter_document_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("work", "Work"),
                    ("floorplan", "Floorplan"),
                    ("finance", "Finance"),
                    ("expense", "Expense"),
                    ("invoice", "Invoice"),
                    ("legal", "Legal"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
