# Generated by Django 5.1.7 on 2025-10-31 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_alter_document_category"),
        ("horsten_homes", "0009_property_purchase_date_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="horsten_homes.property",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("work", "Work"),
                    ("floorplan", "Floorplan"),
                    ("finance", "Finance"),
                    ("expense", "Expense"),
                    ("invoice", "Invoice"),
                    ("leases", "Leases"),
                    ("deeds", "Deeds"),
                    ("legal", "Legal"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
