# Generated by Django 5.1.7 on 2025-10-31 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		("documents", "0012_alter_document_category"),
	]

	operations = [
		migrations.AddField(
			model_name="document",
			name="property",
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documents", to="horsten_homes.property"),
		),
	]


