# Generated by Django 5.1.7 on 2025-10-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_alter_document_category"),
        ("documents", "0013_document_property"),
    ]

    operations = []
