# Generated by Django 5.1.7 on 2025-10-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_document_add_property_fk"),
        ("documents", "0014_merge_20251031_2153"),
    ]

    operations = []
