# Generated by Django 5.1.7 on 2025-09-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_rentalproperty_invoice_rental_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invoicing.rentalproperty')),
            ],
        ),
    ]
