# Generated by Django 5.1.7 on 2025-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_rentalpropertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='levies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='rates_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
