# Generated by Django 5.1.7 on 2025-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_rentalproperty_levies_rentalproperty_rates_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='internet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='water_electricity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
