# Generated by Django 5.1.7 on 2025-09-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0006_rentalproperty_internet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
