# Generated by Django 5.1.7 on 2025-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0007_rentalproperty_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="total_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
