# Generated by Django 5.1.7 on 2025-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0008_rentalproperty_total_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
