# Generated by Django 5.1.7 on 2025-09-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0009_rentalproperty_income"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalproperty",
            name="cost_value",
        ),
    ]
