# Generated by Django 5.1.7 on 2025-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0010_remove_rentalproperty_cost_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalPropertyPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("sold", "Sold"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
