# Generated by Django 5.1.7 on 2025-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0015_managingagent_rentalproperty_managing_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalpropertypipeline",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
