# Generated by Django 5.1.7 on 2025-10-02 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0016_rentalpropertypipeline_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalPropertyPipelineImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rental_property_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="invoicing.rentalpropertypipeline",
                    ),
                ),
            ],
        ),
    ]
