# Generated by Django 5.1.7 on 2025-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0021_rename_rental_to_door"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
