# Generated by Django 5.1.7 on 2025-10-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horsten_homes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Door",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                (
                    "capital_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "flow_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "levies",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rates_taxes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "water_electricity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "internet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_of_money_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "appreciation_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoorPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("sold", "Sold"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EstateAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManagingAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RentalAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="door",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="horsten_homes.door",
            ),
        ),
        migrations.CreateModel(
            name="DoorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rental_property_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="horsten_homes.door",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoorPipelineImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rental_property_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="horsten_homes.doorpipeline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="door",
            name="estate_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estate_properties",
                to="horsten_homes.estateagent",
            ),
        ),
        migrations.AddField(
            model_name="door",
            name="managing_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_properties",
                to="horsten_homes.managingagent",
            ),
        ),
        migrations.CreateModel(
            name="MonthlyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "door",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_expenses",
                        to="horsten_homes.door",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="door",
            name="property_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_properties",
                to="horsten_homes.property",
            ),
        ),
        migrations.AddField(
            model_name="door",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="horsten_homes.rentalagent",
            ),
        ),
    ]
