# Generated by Django 5.1.7 on 2025-10-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "horsten_homes",
            "0002_door_doorpipeline_estateagent_managingagent_property_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="door",
            name="squares",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="door",
            name="total_beds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="door",
            name="total_toilets",
            field=models.IntegerField(default=0),
        ),
    ]
