# Generated by Django 5.1.7 on 2025-11-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("horsten_homes", "0002_attorney_property_attorney"),
        ("horsten_homes", "0002_invoice_add_description"),
    ]

    operations = []
