# Generated by Django 5.1.7 on 2025-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horsten_homes", "0003_door_squares_door_total_beds_door_total_toilets"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="total_bathrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="total_capital_doors",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="property",
            name="total_expense",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="property",
            name="total_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="property",
            name="total_rooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="total_squares",
            field=models.IntegerField(default=0),
        ),
    ]
