# Generated by Django 5.1.7 on 2025-10-31 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		("horsten_homes", "0004_property_total_bathrooms_and_more"),
	]

	operations = [
		migrations.CreateModel(
			name="Tenant",
			fields=[
				("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("name", models.CharField(max_length=200)),
				("email", models.EmailField(blank=True, max_length=254)),
				("phone", models.CharField(blank=True, max_length=50)),
				("move_in_date", models.DateField()),
				("move_out_date", models.DateField(blank=True, null=True)),
				("notes", models.TextField(blank=True)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("door", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tenants", to="horsten_homes.door")),
			],
		),
	]


