# Generated by Django 5.1.7 on 2025-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horsten_homes", "0005_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
