# Generated by Django 5.1.7 on 2025-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("horsten_homes", "0006_alter_tenant_id"),
	]
	
	operations = [
		migrations.AddField(
			model_name="property",
			name="latitude",
			field=models.DecimalField(
				blank=True, decimal_places=6, max_digits=9, null=True
			),
		),
		migrations.AddField(
			model_name="property",
			name="longitude",
			field=models.DecimalField(
				blank=True, decimal_places=6, max_digits=9, null=True
			),
		),
		# migrations.AddField(
		#     model_name="property",
		#     name="property_type",
		#     field=models.CharField(
		#         choices=[
		#             ("commercial", "Commercial"),
		#             ("residential", "Residential"),
		#             ("mixed", "Mixed"),
		#         ],
		#         default="residential",
		#         max_length=20,
		#     ),
		# ),
	]
