# Generated by Django 5.1.7 on 2025-10-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horsten_homes", "0007_property_latitude_property_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("commercial", "Commercial"),
                    ("residential", "Residential"),
                    ("mixed", "Mixed"),
                ],
                default="residential",
                max_length=20,
            ),
        ),
    ]
