# Generated by Django 5.1.7 on 2025-10-31 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horsten_homes", "0008_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="horsten_homes.property",
                    ),
                ),
            ],
        ),
    ]
