# Generated by Django 5.1.7 on 2026-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TideEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("type", models.CharField(max_length=10)),
                ("height", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="stormglass", max_length=100)),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="stormglass", max_length=100)),
                ("air_temperature", models.FloatField(blank=True, null=True)),
                ("water_temperature", models.FloatField(blank=True, null=True)),
                ("dew_point", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("cloud_cover", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(blank=True, null=True)),
                ("visibility", models.FloatField(blank=True, null=True)),
                ("gust", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("wind_direction", models.FloatField(blank=True, null=True)),
                ("wave_height", models.FloatField(blank=True, null=True)),
                ("wave_direction", models.FloatField(blank=True, null=True)),
                ("wave_period", models.FloatField(blank=True, null=True)),
                ("swell_height", models.FloatField(blank=True, null=True)),
                ("swell_direction", models.FloatField(blank=True, null=True)),
                ("swell_period", models.FloatField(blank=True, null=True)),
                ("sea_level", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-timestamp"],
            },
        ),
    ]
