# Generated by Django 5.1.7 on 2025-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="rain",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
