# Generated by Django 5.1.7 on 2025-07-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weatherdata_rain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="current_direction",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="current_speed",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="secondary_swell_direction",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="secondary_swell_height",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="secondary_swell_period",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="uv_index",
        ),
    ]
