# Generated by Django 5.1.7 on 2025-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_remove_weatherdata_current_direction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="rain",
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="dew_point",
            field=models.FloatField(blank=True, default=5, null=True),
        ),
    ]
