# Generated by Django 5.1.7 on 2025-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0004_remove_weatherdata_rain_alter_weatherdata_dew_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="dew_point",
            field=models.FloatField(blank=True, default="25.00", null=True),
        ),
    ]
