# Generated by Django 5.1.7 on 2025-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0006_alter_weatherdata_dew_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="tide_height",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
