# Generated by Django 5.1.7 on 2025-07-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0007_weatherdata_tide_height"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="tide_height",
        ),
    ]
