# Generated by Django 5.1.7 on 2025-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0008_remove_weatherdata_tide_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="TideEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("type", models.CharField(max_length=10)),
                ("height", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="stormglass", max_length=100)),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
