# Generated by Django 5.1.7 on 2025-05-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quick_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("real_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("notes", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("property", "Property"),
                            ("houses", "Houses"),
                            ("cash", "Cash"),
                            ("investments", "Investments"),
                            ("shares", "Shares"),
                            ("valuables", "Valuables"),
                            ("crypto", "Crypto"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
