# Generated by Django 5.1.7 on 2025-05-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worth", "0002_alter_worth_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worth",
            name="category",
            field=models.CharField(
                choices=[
                    ("real_estate", "Real Estate"),
                    ("cash", "Cash"),
                    ("investments", "Investments"),
                    ("shares", "Shares"),
                    ("valuables", "Valuables"),
                    ("crypto", "Crypto"),
                ],
                max_length=50,
            ),
        ),
    ]
