# Generated by Django 5.1.7 on 2025-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worth", "0003_alter_worth_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worth",
            name="category",
            field=models.CharField(
                choices=[
                    ("real_estate", "Real Estate"),
                    ("cash", "Cash"),
                    ("business", "Business"),
                    ("investments", "Investments"),
                    ("shares", "Shares"),
                    ("valuables", "Valuables"),
                    ("crypto", "Crypto"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="worth",
            name="quick_value",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="worth",
            name="real_value",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
