# Generated by Django 5.1.7 on 2025-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worth", "0004_alter_worth_category_alter_worth_quick_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worth",
            name="quick_value",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="worth",
            name="real_value",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
