# Generated by Django 5.1.7 on 2025-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("is_online", models.BooleanField(default=True)),
                ("drop_count", models.PositiveIntegerField(default=0)),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
