# Generated by Django 5.1.7 on 2026-01-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("is_online", models.BooleanField(default=True)),
                ("drop_count", models.PositiveIntegerField(default=0)),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PingControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("ip", models.GenericIPAddressField()),
                ("status", models.CharField(max_length=10)),
                ("latency", models.FloatField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ping_results",
                        to="monitoring.monitoreddevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
