# Generated by Django 5.1.7 on 2025-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_pingresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="PingControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="pingresult",
            name="ip",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pingresult",
            name="latency",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pingresult",
            name="status",
            field=models.CharField(default="1.1.1.1", max_length=10),
            preserve_default=False,
        ),
    ]
