# Generated by Django 5.1.7 on 2025-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_pingcontrol_pingresult_ip_pingresult_latency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pingresult",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
