# Generated by Django 5.1.7 on 2025-07-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_pingresult_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pingresult",
            name="active",
        ),
    ]
