# Generated by Django 5.1.7 on 2025-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
