# Generated by Django 5.1.7 on 2025-05-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CryptoStats",
        ),
    ]
