# Generated by Django 5.1.7 on 2025-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0002_cryptorecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "exchange",
                    models.CharField(
                        choices=[("binance", "Binance"), ("luno", "Luno")],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
