# Generated by Django 5.1.7 on 2025-04-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0003_cryptostats"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CryptoRecord",
        ),
    ]
