# Generated by Django 5.1.7 on 2025-04-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0004_delete_cryptorecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptostats",
            name="exchange",
        ),
    ]
